import { sampleAscii } from "./byteScan";
import type {
  AiDetectionResult,
  GeneratorName,
  GeneratorResult,
  MetadataResult,
  ProvenanceResult,
} from "./types";

/**
 * Pluggable interface for an external AI-detection model/API.
 * No provider is configured by default — AIMD reports "unavailable" rather
 * than fabricating a score. Register a real implementation here to enable it.
 */
export interface AiDetectionProvider {
  name: string;
  detect(file: File): Promise<{ probability: number; confidence: number; reasons: string[] }>;
}

let provider: AiDetectionProvider | null = null;
export function registerAiDetectionProvider(p: AiDetectionProvider) {
  provider = p;
}
export function getAiDetectionProvider(): AiDetectionProvider | null {
  return provider;
}

/** Software/XMP strings that are direct, self-declared generator evidence. */
const GENERATOR_SIGNATURES: Array<{ needle: string; generator: GeneratorName; evidence: string }> = [
  { needle: "openai", generator: "OpenAI / ChatGPT", evidence: "\"openai\" string embedded in file metadata" },
  { needle: "dall-e", generator: "DALL·E", evidence: "\"dall-e\" string embedded in file metadata" },
  { needle: "dalle", generator: "DALL·E", evidence: "\"dalle\" string embedded in file metadata" },
  { needle: "midjourney", generator: "Midjourney", evidence: "\"midjourney\" string embedded in file metadata" },
  { needle: "gemini", generator: "Google Gemini", evidence: "\"gemini\" string embedded in file metadata" },
  { needle: "imagen", generator: "Google Gemini", evidence: "Google Imagen marker embedded in file metadata" },
  { needle: "firefly", generator: "Adobe Firefly", evidence: "Adobe Firefly marker embedded in file metadata" },
  { needle: "stable diffusion", generator: "Stable Diffusion", evidence: "Stable Diffusion marker in metadata" },
  { needle: "stable-diffusion", generator: "Stable Diffusion", evidence: "Stable Diffusion marker in metadata" },
  { needle: "automatic1111", generator: "Stable Diffusion", evidence: "AUTOMATIC1111 parameters block present" },
  { needle: "comfyui", generator: "Stable Diffusion", evidence: "ComfyUI workflow block present" },
  { needle: "flux.1", generator: "Flux", evidence: "Flux model marker in metadata" },
  { needle: "black forest labs", generator: "Flux", evidence: "Black Forest Labs marker in metadata" },
];

const GENERIC_AI_MARKERS = [
  "trainedalgorithmicmedia",
  "ai_generated",
  "ai-generated",
  "generativeai",
  "generated by ai",
  "sref",
  "prompt=",
];

export interface SignalScan {
  generatorHits: Array<{ generator: GeneratorName; evidence: string }>;
  genericHits: string[];
}

export function scanAiSignals(bytes: Uint8Array): SignalScan {
  const text = sampleAscii(bytes).toLowerCase();
  const generatorHits: Array<{ generator: GeneratorName; evidence: string }> = [];
  for (const sig of GENERATOR_SIGNATURES) {
    if (text.includes(sig.needle)) generatorHits.push({ generator: sig.generator, evidence: sig.evidence });
  }
  const genericHits = GENERIC_AI_MARKERS.filter((m) => text.includes(m));
  return { generatorHits, genericHits };
}

/**
 * Combines hard, verifiable signals (provenance + embedded generator strings)
 * with an optional external detection provider. Never returns a synthetic score.
 */
export async function detectAi(
  file: File,
  scan: SignalScan,
  provenance: ProvenanceResult,
  metadata: MetadataResult,
): Promise<AiDetectionResult> {
  const reasons: string[] = [];
  const hardEvidence =
    provenance.aiIndicated === true || scan.generatorHits.length > 0 || scan.genericHits.length > 0;

  if (provenance.aiIndicated === true)
    reasons.push("Content Credentials declare trained-algorithmic (AI) media");
  scan.generatorHits.forEach((h) => reasons.push(h.evidence));
  scan.genericHits.forEach((h) => reasons.push(`Generic AI marker "${h}" present in file`));

  if (provider) {
    try {
      const r = await provider.detect(file);
      reasons.push(...r.reasons);
      return {
        state: r.probability >= 0.6 ? "generated" : r.probability <= 0.3 ? "authentic" : "inconclusive",
        probability: Math.round(r.probability * 100),
        confidence: Math.round(r.confidence * 100),
        serviceName: provider.name,
        serviceConfigured: true,
        reasons,
        message: "Result produced by the configured AI-detection model combined with embedded signals.",
      };
    } catch {
      reasons.push("Configured AI-detection service returned an error");
    }
  }

  if (hardEvidence) {
    // Confidence derives only from how many independent hard signals agree.
    const signals =
      (provenance.aiIndicated === true ? 1 : 0) +
      (scan.generatorHits.length > 0 ? 1 : 0) +
      (scan.genericHits.length > 0 ? 1 : 0);
    const confidence = signals >= 3 ? 92 : signals === 2 ? 84 : 72;
    return {
      state: "generated",
      probability: confidence,
      confidence,
      serviceName: "AIMD embedded-signal analysis",
      serviceConfigured: false,
      reasons,
      message:
        "AI-generation indicators were found directly inside the file. No external detection model is configured, so pixel-level analysis was not performed.",
    };
  }

  if (metadata.available && metadata.device.identified) {
    reasons.push("Camera make/model EXIF tags consistent with a hardware capture");
    reasons.push("No embedded AI-generation markers or provenance found");
    return {
      state: "authentic",
      probability: 0,
      confidence: 74,
      serviceName: "AIMD embedded-signal analysis",
      serviceConfigured: false,
      reasons,
      message:
        "No strong AI-generation indicators were found and camera metadata is present. This is not a pixel-level model verdict.",
    };
  }

  return {
    state: "inconclusive",
    probability: null,
    confidence: null,
    serviceName: "AIMD embedded-signal analysis",
    serviceConfigured: false,
    reasons: [
      "No embedded AI-generation markers found",
      "No camera metadata available to support authenticity",
      "No external AI-detection model configured",
    ],
    message:
      "AI detection service unavailable — the available evidence is insufficient to reach a conclusion.",
  };
}

export function identifyGenerator(
  scan: SignalScan,
  provenance: ProvenanceResult,
  metadata: MetadataResult,
): GeneratorResult {
  const evidence: string[] = [];
  let generator: GeneratorName | null = null;
  let confidence: number | null = null;

  if (provenance.application) {
    const match = GENERATOR_SIGNATURES.find((s) =>
      provenance.application!.toLowerCase().includes(s.needle),
    );
    generator = match?.generator ?? null;
    if (generator) {
      evidence.push(`Content Credentials name the producing application: ${provenance.application}`);
      confidence = 88;
    }
  }

  if (!generator && scan.generatorHits.length > 0) {
    generator = scan.generatorHits[0]!.generator;
    evidence.push(...scan.generatorHits.map((h) => h.evidence));
    confidence = scan.generatorHits.length > 1 ? 78 : 70;
  }

  const software = metadata.device.software;
  if (software) {
    const match = GENERATOR_SIGNATURES.find((s) => software.toLowerCase().includes(s.needle));
    if (match) {
      generator = generator ?? match.generator;
      evidence.push(`EXIF Software tag: "${software}"`);
      confidence = Math.max(confidence ?? 0, 80);
    }
  }

  if (!generator) {
    return {
      determined: false,
      generator: null,
      confidence: null,
      evidence: [],
      message: "AI source could not be determined.",
    };
  }

  return {
    determined: true,
    generator,
    confidence,
    evidence,
    message:
      "Identification is based on evidence embedded in the file and is reported as a possibility, not a certainty.",
  };
}
